FROM harbor.galasa.dev/docker_proxy_cache/library/httpd:alpine

RUN rm -v /usr/local/apache2/htdocs/*
COPY dockerfiles/httpdconf/base-httpd.conf /usr/local/apache2/conf/httpd.conf

COPY bin/galasactl* /usr/local/apache2/htdocs/